version: '3.8' 

services:
  db:
    image: postgres:15-alpine 
    container_name: mi_postgres_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mi_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  api:
    build: . 
    container_name: mi_fastapi_app
    ports:
      - "8000:8000" 
    depends_on:
      - db 
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/mi_api_db

volumes:
  postgres_data: