name: CI de API - Pruebas y Construcci칩n

#Disparadores (Triggers)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  test-y-build:
    # Se ejecuta en una m치quina virtual Ubuntu 
    runs-on: ubuntu-latest

    
    steps:
    # "Checkout" del c칩digo fuente del repositorio
    - name: Checkout del c칩digo
      uses: actions/checkout@v4

    # Configura Python
    - name: Configurar Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Instala dependencias
 
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    #Ejecuta las pruebas
    
    - name: Ejecutar Pruebas con Pytest
      run: |
        pytest
    
  
    - name: Construir la imagen Docker
      run: |
        docker build . --tag mi-api-test